PhoneBook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('phonebook.urls')),
    path('auth/', include('social_django.urls')),
]

phonebook/urls.py
from django.urls import path
from .views import *

app_name = 'phone_book'

urlpatterns = [
    path('logins/', logins, name='login'),
    path('log_out/', log_out, name='logout'),
    path('tog_fav/<int:id>', toggle_favourite, name='tog_fav'),
    path('del_contact/<int:id>', delete_contact, name='del_contact'),
    path('all/', ContactDetails.as_view(), name='contact_details'),
    path('update/<int:pk>', ContactUpdate.as_view(), name='contact_update'),
    path('delete_multi/', delete_multi, name='delete_multi'),
    path('import_vcf/', import_vcf, name='import_vcf'),
    path('report_lab/pdf/', write_pdf_view, name='report'),
    path('report/pdf/', html_to_pdf_view, name='report'),
]

phonebook/models.py
from django.contrib.auth.models import User
from django.db import models
from django_countries.fields import CountryField
from django_extensions.db.models import TimeStampedModel


class Contact(TimeStampedModel):
    fname = models.CharField(max_length=30, verbose_name='First Name')
    lname = models.CharField(max_length=30, verbose_name='Sur Name', blank=True, null=True)
    nick_name = models.CharField(max_length=30, verbose_name='Nick Name', null=True, blank=True)
    company_name = models.CharField(max_length=30, null=True, verbose_name='Company', blank=True)
    email = models.EmailField(max_length=30, null=True, blank=True)
    website = models.CharField(max_length=50, null=True, blank=True)
    bdate = models.DateField(null=True, verbose_name='Birth Date', blank=True)
    is_favourite = models.BooleanField(default=False, verbose_name='Favourite')
    user_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.fname


class ContactNo(TimeStampedModel):
    number = models.CharField(max_length=13)
    number_type = models.CharField(choices=[('mobile', 'Mobile'), ('tel', 'Telephone'), ('fax', 'Fax')],
                                   max_length=6, default='mobile')
    contact_id = models.ForeignKey(Contact, on_delete=models.CASCADE, related_name='number_ids', null=True, blank=True)

    def __str__(self):
        return self.contact_id.fname + ' - '+ self.number


class Address(TimeStampedModel):
    street = models.TextField(max_length=60)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    country = CountryField()
    zip = models.CharField(max_length=6)
    type = models.CharField(choices=[('home', 'Home'), ('work', 'Work')], max_length=6)
    contact_id = models.ForeignKey(Contact, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.type + ' - ' + self.contact_id.fname

phonebook/forms.py
from crispy_forms.helper import FormHelper
from django.contrib.auth.models import User
from django import forms
from .models import *
from django.forms.models import inlineformset_factory
from .custom_layout_object import *
from crispy_forms.layout import Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit, Row, Column


class LoginForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.TextInput(attrs={
        'type': 'password'
    }))

    class Meta:
        model = User
        fields = ['email', 'password']


class ContactForm(forms.ModelForm):
    bdate = forms.DateField(label='Birth Date', required=False, widget=forms.TextInput(
        attrs={
            'type': 'date',
        })) # Require to show date widget in form

    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        # form helper use for custom designing and add bootstrap classes dynamiccaly into forms after render into html
        self.helper.layout = Layout(
            Row(
                Column('fname', css_class='form-group col-md-6 mb-0'),
                Column('lname', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('email', css_class='form-group col-md-6 mb-0'),
                Column('bdate', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('company_name', css_class='form-group col-md-6 mb-0'),
                Column('website', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Fieldset('Add Contact Numbers', Formset('contacts')),
            Submit('submit', 'Save')
        )


class ContactNoForm(forms.ModelForm):
    class Meta:
        model = ContactNo
        exclude = () # we can also use fields = '__all__'


ContactNoFormSet = inlineformset_factory(
    Contact, ContactNo, form=ContactNoForm,
    fields=['number', 'number_type'], extra=1, can_delete=True
)


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['contact_id']

phonebook/views.py
from io import BytesIO

import vobject
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.views.generic import CreateView, UpdateView
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Spacer, Paragraph
import weasyprint
from .forms import *
from django.db import transaction
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .document import *


def html_to_pdf_view(request):
    contacts = Contact.objects.all()
    contact_data = [
        {
            'id': c.id,
            'name': c.fname + ' ' + (c.lname if c.lname else ''),
            'email': c.email if c.email else '-',
            'is_favourite': c.is_favourite,
            'ph_numbers': [cn.number for cn in ContactNo.objects.filter(contact_id=c.id)]
        }
        for c in contacts
    ]

    html_string = render_to_string('phonebook/report.html', {'data': contact_data})

    html = weasyprint.HTML(string=html_string)
    html.write_pdf(target='/tmp/mypdf.pdf')

    fs = FileSystemStorage('/tmp')
    with fs.open('mypdf.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'
        return response

    return response


def write_pdf_view(request):
    doc = SimpleDocTemplate("/tmp/somefilename.pdf")
    styles = getSampleStyleSheet()
    Story = [Spacer(1, 2 * inch)]
    style = styles["Normal"]
    for i in range(100):
        bogustext = ("This is Paragraph number %s.  " % i) * 20
        p = Paragraph(bogustext, style)
        Story.append(p)
        Story.append(Spacer(1, 0.2 * inch))
    doc.build(Story)

    fs = FileSystemStorage("/tmp")
    with fs.open("somefilename.pdf") as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'
        return response

    return response


class ContactDetails(LoginRequiredMixin, CreateView):
    model = Contact
    template_name = 'phonebook/contact_data.html'
    form_class = ContactForm
    success_url = None
    login_url = '/logins/'

    def get_context_data(self, **kwargs):
        # contacts = ContactDocument.search(index='contacts').scan()
        contacts = Contact.objects.all()
        contact_data = [
            {
                'id': c.id,
                'name': c.fname + ' ' + (c.lname if c.lname else ''),
                'email': c.email if c.email else '-',
                'is_favourite': c.is_favourite,
                'ph_numbers': [cn.number for cn in ContactNo.objects.filter(contact_id=c.id)]
            }
            for c in contacts
        ]
        kwargs.update({'data': contact_data})
        data = super(ContactDetails, self).get_context_data(**kwargs)
        if self.request.POST:
            data['contacts'] = ContactNoFormSet(self.request.POST)
        else:
            data['contacts'] = ContactNoFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        numbers = context['contacts']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            self.object = form.save()
            if numbers.is_valid():
                numbers.instance = self.object
                numbers.save()
        return super(ContactDetails, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('phone_book:contact_details')


class ContactUpdate(UpdateView):
    model = Contact
    template_name = 'phonebook/contact_data.html'
    form_class = ContactForm
    success_url = None

    def get_context_data(self, **kwargs):
        contacts = ContactDocument.search(index='contacts').scan()
        contact_data = [
            {
                'id': c.id,
                'name': c.fname + ' ' + (c.lname if c.lname else ''),
                'email': c.email if c.email else '-',
                'is_favourite': c.is_favourite,
                'ph_numbers': [cn.number for cn in ContactNo.objects.filter(contact_id=c.id)]
            }
            for c in contacts
        ]
        kwargs.update({'data': contact_data})
        data = super(ContactUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['contacts'] = ContactNoFormSet(self.request.POST, instance=self.object)
        else:
            data['contacts'] = ContactNoFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        numbers = context['contacts']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            self.object = form.save()
            if numbers.is_valid():
                numbers.instance = self.object
                numbers.save()
        return super(ContactUpdate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('phone_book:contact_details', kwargs={'pk': self.object.pk})


def logins(request):
    if request.user.id and request.user.is_authenticated:
        return redirect('phone_book:contact_details')
    elif request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user = authenticate(username=login_form.cleaned_data['email'], password=login_form.cleaned_data['password'])
            if user:
                login(request, user)
                return redirect('phone_book:contact_details')
            else:
                return redirect('phone_book:login')
    else:
        login_form = LoginForm()
        return render(request, 'phonebook/login.html', {'form': login_form})


def log_out(request):
    logout(request)  # It will logout user and clear current login sessions
    return redirect('phone_book:login')


@login_required
def delete_contact(request, id):
    """ This method use for delete contact to favourite and its request type is AJAX """
    contact = Contact.objects.get(pk=id)
    contact.delete()
    return JsonResponse({'success': True})


@login_required
def toggle_favourite(request, id):
    """ This method use for add contact to favourite and its request type is AJAX """
    contact = Contact.objects.get(pk=id)
    contact.is_favourite = not contact.is_favourite
    contact.save()
    return JsonResponse({'success': True, 'fav_value': contact.is_favourite})


def delete_multi(request):
    if request.POST and request.is_ajax:
        contact_ids = dict(request.POST).get("ids[]")
        contacts = Contact.objects.filter(pk__in=contact_ids)
        print("Contacts", [c.fname for c in contacts])
        # contacts.delete()
        return JsonResponse({"success": True, "contacts": contact_ids})


@login_required
def import_vcf(request):
    if request.is_ajax() and request.method == "POST" and request.FILES:
        file = request.FILES.get('vcf_file')
        if file and file.name[-4:] in ['.vcf', '.csv']:
            with file as f:
                vc = vobject.readComponents(f.read().decode("utf-8"))
                vo = next(vc, None)
                while vo is not None:
                    # vo.prettyPrint()
                    fname = vo.contents.get('fn')[0].value
                    email = vo.contents.get('email')[0].value if vo.contents.get('email') else ''
                    numbers = []
                    if vo.contents.get('tel'):
                        for v in vo.contents['tel']:
                            no = v.value.replace("-", "")
                            if no not in numbers and no[-10:] not in numbers[-10:]:
                                numbers.append(no)
                    print(fname, ', ', numbers, ', ', email)
                    vo = next(vc, None)
                    # TODO: Bulk creation and code optimization
                    contact = Contact.objects.create(fname=fname, email=email)
                    if numbers:
                        for number in numbers:
                            ContactNo.objects.create(number=number, number_type='mobile', contact_id=contact)

            return redirect("phone_book:contact_details")

        else:
            return JsonResponse({'success': False, 'message': 'Only vcf or csv files are allowed'})
    else:
        return JsonResponse({'success': False})


def contact_data(request):
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        contact_no_form = ContactNoForm(request.POST)
        if contact_form.is_valid() and contact_no_form.is_valid():
            fname = contact_form.cleaned_data.get('fname')
            lname = contact_form.cleaned_data.get('lname')
            nick_name = contact_form.cleaned_data.get('nick_name')
            email = contact_form.cleaned_data.get('email')
            website = contact_form.cleaned_data.get('website')
            company_name = contact_form.cleaned_data.get('company_name')
            bdate = contact_form.cleaned_data.get('bdate')

            number = contact_no_form.cleaned_data.get('number')
            number_type = contact_no_form.cleaned_data.get('number_type')

            contact = Contact.objects.create(fname=fname, lname=lname, nick_name=nick_name, email=email,
                                             website=website, company_name=company_name, bdate=bdate)

            ContactNo.objects.create(number=number, number_type=number_type, contact_id=contact)

    contact_form = ContactForm()
    contact_no_form = ContactNoForm()

    contacts = Contact.objects.all()
    contact_data = [
        {
            'id': c.id,

templates/phonebook/base.html
{% load staticfiles %}
<html>

<head>
    <title>Contacts</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>

    <div class="row">
        <div class="col-md-11"></div>
        <div class="col-md-1 pull-right" style="margin-top:10px;">
            <a href="{% url 'phone_book:logout' %}" class="btn btn-sm btn-secondary">Logout</a>
        </div>
    </div>

    <div class="container">

        {% block content %}

        {% endblock %}


    </div>



    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/phonebook/contact_create.html
{% load crispy_forms_tags %}
{% load staticfiles %}

<html>
    <head>
        <title>Test Formset</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    </head>

    <body>

        <div class="container">
            <div class="card">
                <div class="card-header">
                    Create collection
                </div>
                <div class="card-body">
                     {% crispy form %}
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    </body>

</html>

templates/phonebook/contact_data.html
{% extends "phonebook/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
<!--        <div class="row">-->
<!--            <div class="col-md-12">-->
<!--                <div class="row justify-content-center">-->
<!--                    <div class="col-12 col-md-10 col-lg-8">-->
<!--                        <div class="card-body row no-gutters align-items-center">-->
<!--&lt;!&ndash;                        <div class="col-auto">&ndash;&gt;-->
<!--                            <i class="fa h1 fa-search text-body"></i>-->
<!--                        </div>-->
<!--                            <div class="col">-->
<!--                                <input class="form-control form-control-borderless" type="search" placeholder="Search Contacts">-->
<!--                            </div>-->
<!--                            &nbsp;-->
<!--                            <div class="col-auto">-->
<!--                                <button class="btn btn-info" type="submit">Search</button>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
    <br/>

    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="row">
                    <div class="col-md-12">
                        <button class="btn btn-info btn-sm" data-target="#modal_contact" data-toggle="modal">
                            Create New
                        </button>
                    </div><br/><br/>
                    <div class="col-md-12">
                        <button class="btn btn-info btn-sm">
                            Synchronize
                        </button>

                    </div><br/><br/>
                    <div class="col-md-12">
                        <button class="btn btn-info btn-sm" data-target="#modal_imp_contact" data-toggle="modal">
                            Import
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <table id="contact_table" class="table table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Name</th>
                            <th>Phone Number</th>
                            <th>Email</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in data %}
                            <tr>
                                <td>
                                    <input type="checkbox" data='{{ c.id }}' class="select-multiple">
                                </td>
                                <td>{{ c.name }} </td>
                                <td>
                                    {% if c.ph_numbers %}
                                        {{ c.ph_numbers.0 }}
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                                <td>{{ c.email }}</td>
                                <td>
                                    <a href="{% url 'phone_book:contact_update' c.id %}" name="a_edit" data-target="#modal_contact">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'phone_book:del_contact' c.id %}" name="a_remove">
                                        <i class="fa fa-remove"></i>
                                    </a></td>
                                <td>
                                    <a href="{% url 'phone_book:tog_fav' c.id %}" name="a_fav">
                                        {% if c.is_favourite == True %}
                                            <i class="fa fa-star"></i>
                                        {% else %}
                                            <i class="fa fa-star-o"></i>
                                        {% endif %}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>


    <div class="modal fade" id="modal_contact">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="card">
                        <div class="card-header">
                            Create contacts
                        </div>
                        <div class="card-body">
                             {% crispy form %}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
<!--                    <button type="button" class="close" data-dismiss="modal">&times;</button>-->
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal_imp_contact">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="card">
                        <div class="card-header">
                            Import contacts
                        </div>
                        <div class="card-body">
                             <form method="post" id="form_import_vcf" action="{% url 'phone_book:import_vcf' %}" enctype="multipart/form-data">
                                 {% csrf_token %}
                                 <div id="form-group">
                                     <label for="vcf_file">
                                         <input type="file" name="vcf_file" id="vcf_file" accept=".csv,.vcf" required/>
                                     </label>
                                     <input type="submit" class="btn btn-success btn-sm" value="Import"/>
                                 </div>
                             </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/phonebook/formset.html
{% load crispy_forms_tags %}
{% load staticfiles %}
<table class="col-md-9" style="margin-left: 10px;">
{{ formset.management_form|crispy }}

    {% for form in formset.forms %}
            <tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
                {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                </td>
                {% endfor %}
            </tr>
    {% endfor %}

</table>
<br>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'add another',
        deleteText: 'remove',
        prefix: '{{ formset.prefix }}',
    });
</script>

templates/phonebook/login.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<html>

<head>
    <title>Contacts</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <center><h2>Login</h2></center>
            </div>
        </div>

        <form action="{% url 'phone_book:login' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.password|as_crispy_field }}
                    </div>
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <center>
                        <input type="submit" value="Login" class="btn btn-info btn-sm">
                        <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-info btn-sm">Login with Google</a>
                        <a href="{% url 'social:begin' 'linkedin-oauth2' %}" class="btn btn-info btn-sm">Login with LinkedIn</a>
                        <a href="{% url 'social:begin' 'facebook' %}" class="btn btn-info btn-sm">Login with Facebook</a>
                    </center>
                </div>
                <div class="col-md-3"></div>
            </div>
        </form>
    </div>

</body>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
</html>